version: "3.7"

# USE ——PARALLEL FOR BUILDING

services:
  slashbackend:
    build:
      context: .
      dockerfile: "apps/slashbackend/Dockerfile"
    depends_on:
      - postgres
      - redis
      - voicenode
      - meili
    ports:
      - "9999:8080"
      - "9229:9229"  
    networks:
      - databases
      - backend
      - meili
      - minio
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      DISCORD_APP_ID: ${DISCORD_APP_ID}
      DISCORD_PUBLIC_KEY: ${DISCORD_PUBLIC_KEY}
      DISCORD_TOKEN: ${DISCORD_TOKEN}

  voicenode:
    build:
      context: .
      dockerfile: "apps/voicenode/Dockerfile"
    expose:
      - "8888"
    networks:
      - backend
      - minio
      - databases
    depends_on:
      - minio
      - postgres
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  voteserver:
    build:
      context: .
      dockerfile: "apps/voteserver/Dockerfile"
    expose:
      - "7777"
    networks:
      - backend
      - databases
    depends_on:
      - minio
      - postgres
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


  bot:
    build:
      context: .
      dockerfile: "apps/bot/Dockerfile"
    networks:
      - minio
      - databases
      - meili
    depends_on:
      - minio
      - postgres
      - redis
      - meili
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      DISCORD_APP_ID: ${DISCORD_APP_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}

  redis:
    image: "redis:alpine"
    volumes:
      - databases:/data
    networks:
      - databases
    expose:
      - "6379"
    # ! REMOVE
    ports:
      - "6379:6379"    
    command: redis-server --requirepass ${REDIS_PASSWORD}
    
  postgres:
    image: "postgres:alpine"
    volumes:
      - databases:/var/lib/postgres
    networks:
      - databases
    expose:
      - "5432"
    # ! REMOVE
    ports:
      - "5431:5432"  
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  minio:
    image: minio/minio
    command: server /data --console-address :9001
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    expose:
      - "9000"
    # ! REMOVE
    ports:
      - "9000:9000"
      - "9001:9001"  
    networks:
      - minio

  meili:
    image: getmeili/meilisearch
    user: "root"
    environment:
    
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    expose:
      - "7700"
    networks:
      - meili
    volumes:
      - meili:/home/meili/data.ms
    ports:
      - "7700:7700"  

networks:
  databases:
  backend:
  minio:
  meili:

volumes:
  databases:
  meili:
  minio:
