name: Test
on: [push]
jobs:
  lint:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Install ffmpeg
        run: sudo apt-get update ; sudo apt-get install ffmpeg

      - name: Install dependencies
        run: yarn && yarn run build

      - name: Run Tests
        run: yarn run test
